### ISSUE TITLE
3 Messages Properly Tagged, But Alerted Adrian

### ISSUE THREAD

**Issue by d4mation** [realbig/PL_PYIS_ADDRESS_COLLECTION#10]
_From @BigActual on April 21, 2018 18:58_

This came from Adrian last Sunday. Though it is on the docket, it did not get entered as an issue. For tracking purposes, I'm adding it in. 
Adrian [6:02]
Hi Steve -- sorry to ping you on a Sunday but I'm planning on taking a few days off at the end of the week so I'm getting a jump on things.

Eric updated the plugin so that it properly sends email notifications; however, there is still a problem. I woke up this morning and found three email notifications for people who are properly tagged in Drip but the plugin alerted me for:

adrian [6:03 AM]
uploaded this image: Screen Shot 2018-04-15 at 5.16.13 AM.png

adrian [6:03 AM]
This has been happening for the past few weeks.
The plugin needs a round of heavy debugging. I'm happy to pay for it of course, but it needs actually updating and testing. Let me know if you can schedule any time for this, and if so, when.

big_actual [1:43 PM]
shared adrian’s image: Screen Shot 2018-04-15 at 5.16.13 AM.png 

_Copied from original issue: Py-Image/comment-assignment#5_

**Comment by d4mation** [comment]
_From @jrosebr1 on April 22, 2018 11:18_

Hey @BigActual -- this ticket should actually be for the address collection plugin:

https://github.com/Py-Image/PL_PYIS_ADDRESS_COLLECTION

Additionally, I have a second physical book that I am shipping out. I need this plugin to work with another CognitoForms URL and another tag.

The bug label from Steve's initial ticket is correct but additional functionality needs to be added as well.

**Comment by d4mation** [comment]
_From @BigActual on April 22, 2018 11:31_

Moved.

**Comment by d4mation** [comment]
@jrosebr1 

I believe I have this fixed with [v1.1.0b1](https://github.com/Py-Image/PL_PYIS_ADDRESS_COLLECTION/releases/tag/v1.1.0b1)

I included a little bit of debugging info fed back through the email address which should help alert you in the event that Account ID/API Key/Password are incorrect and other errors returned from the API. That ended up helping me a bit in debugging this.

An easy way to test this without needing to fill out the Cognito Form repeatedly would be to paste the following into your Terminal (With values swapped out as appropriate)

```
curl -X POST -H "Content-type: application/json" -d '{"Form":{"Id":"1","InternalName":"PracticalPythonAndOpenCVHardcopyShipping","Name":"Practical Python and OpenCV Hardcopy Shipping"},"$version":6,"$etag":"W/\"datetime'2018-04-23T17%3A16%3A48.8152562Z'\"","Entry":{"AdminLink":"admin-link","DateSubmitted":"2018-04-23T17:16:48.639Z","DateUpdated":"2018-04-23T17:16:48.639Z","EditLink":"edit-link","LastPageViewed":null,"Number":25,"Order":null,"Origin":{"City":null,"CountryCode":null,"IpAddress":"68.48.236.212","IsImported":false,"Region":null,"Timezone":null,"UserAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"},"PaymentToken":null,"Status":"Submitted","Timestamp":"2018-04-23T17:16:48.639Z","ViewLink":"view-link"},"Id":"1-25","AreYouShippingToTheUnitedStates":true,"Email":"fakefake@fake.com","Name":{"First":"Eric","FirstAndLast":"Eric Defore","Last":"Defore","Middle":null,"MiddleInitial":null,"Prefix":null,"Suffix":null},"Address":{"City":"Fake","CityStatePostalCode":"Fake, Michigan 49418","Country":"United States","FullAddress":"Fake, Fake, Michigan 49418","FullInternationalAddress":"Fake, Fake, Michigan 49418, United States","Latitude":0.0,"Line1":"Fake","Line2":null,"Line3":null,"Longitude":0.0,"PostalCode":"49418","State":"Michigan","StreetAddress":"Fake","Type":"Home"},"Address2":{"City":null,"CityStatePostalCode":"","Country":"United States","FullAddress":"","FullInternationalAddress":"United States","Latitude":0.0,"Line1":null,"Line2":null,"Line3":null,"Longitude":0.0,"PostalCode":null,"State":null,"StreetAddress":"","Type":"Home"},"Secret":<YOUR SECRET KEY>}' <YOUR_WEBSITE>/wp-json/pyis/v1/cognitoforms/practical-python-open-cv-hardcopy/submit
```

This plugin only cares about the following values in the JSON, so you can adjust these to alter output for testing with Drip Subscribers who did purchase the book, did not purchase the book, etc. The Email Field is what is used for querying Drip and the rest is just for additional flavor in Emails and such, so those can be whatever you'd like.

```
$form_name = $json->Form->Name;
$entry_id = $json->Entry->Number;
$entry_link = $json->Entry->AdminLink;
        
$email = $json->Email;
$first_name = $json->Name->First;
$last_name = $json->Name->Last;
```

Once we know that this is good, we can begin work on #9. #9 will require some restructuring to the API Calls, so I want to ensure that what we have now is working properly :+1:

**Comment by jrosebr1** [comment]
@d4mation 

Nice! I just installed it on the server and use the example `curl` command you provided. I included the secret key for the form along with the server URL. I got a success message back from the server using a fake email address:

```
"{\"success\":true,\"message\":\"Success!\"
```

But no email alert saying there was a suspicious entry.

If we're going to beta test this I think we should have the plugin send an email out for each entry it receives and inside the email it can say whether:

1. Everything is okay, the reader purchased, and the plugin + Drip know this
2. Everything is not okay, Drip is reporting that the reader did not purchase

This will enable us to debug both ends. Once we're confident that everything is working we can remove the first email but keep the second one.

**Comment by d4mation** [comment]
@jrosebr1 

I can add those email alerts. 

That "Success" message JSON gets returned whenever the the cURL request succeeds no matter what happens. That means that an email _should_ have been sent out for it being suspicious in your case. Are you testing on Staging? If so, do you have the "Stop Emails" plugin active?

**Comment by jrosebr1** [comment]
@d4mation 

Yes, I am on the staging server. I do still have the "Stope Emails" plugin activated. I cannot turn it off otherwise the membership plugin will start sending out email alerts. I think we decided to (purposely) use `mail` instead of `wp_mail` for this plugin? Correct me if I'm wrong. I know it's not the best development practice for WP but for the time being it's the best way to test.

**Comment by d4mation** [comment]
We decided to temporarily use `mail()` rather than `wp_mail()` and then switched it to `wp_mail()` once it went Live. I can switch it back to `mail()` for the time being though.

**Comment by jrosebr1** [comment]
Yes, let's please use `mail` for the test.

As a feature request that would be a nice radio or checkbox to have in the `/wp-admin` -- use either `mail` or `wp_mail`.

**Comment by d4mation** [comment]
@jrosebr1 

I went ahead and added the option for using `mail()` rather than `wp_mail()` as well as made the cURL response messages more explicit in what was accomplished, which should remove the need for that first email you were talking about which would have been temporarily added. The second one is already a part of the code base.

Let me know if you've still got problems! https://github.com/Py-Image/PL_PYIS_ADDRESS_COLLECTION/releases/tag/v1.1.0b2

**Comment by jrosebr1** [comment]
@d4mation 

Thanks, I just installed it. I couldn't find the `mail` vs. `wp_mail` in the plugin settings though. But when I tested it using `curl` the email went out so I assume it's now using `mail`.

**Comment by d4mation** [comment]
It should be on the Settings page for the Address Collection plugin as the last option.

By default it uses `wp_mail()`, so it is odd that it worked for you.

![image](https://user-images.githubusercontent.com/7770631/39315603-1607ced2-4945-11e8-80c6-e65d1c8220bb.png)

**Comment by jrosebr1** [comment]
See screenshot below.

(just going to delete the screenshot now)

**Comment by d4mation** [comment]
Did you grab the ZIP from `develop` or otherwise grab the pre-packaged Release ZIP from the link I posted above? I'm wondering if you grabbed `master` instead.

**Comment by jrosebr1** [comment]
I grabbed it from the following link:

https://github.com/Py-Image/PL_PYIS_ADDRESS_COLLECTION/releases/tag/v1.1.0b2

**Comment by d4mation** [comment]
That is very strange. I just did the same to confirm and I see the new option. 

You're clicking this link, right? Technically they all should work, but I package up the Releases using that first link to remove some dev-only files for a smaller file size.

![image](https://user-images.githubusercontent.com/7770631/39317667-2a6133a0-494a-11e8-94bb-c5295831c187.png)

**Comment by jrosebr1** [comment]
Yes. I just downloaded and re-installed to confirm.

Do you still have access to the testing server? I can get you the credentials over Slack.

**Comment by d4mation** [comment]
For documentation/future reference: This was caused by a second copy of the plugin existing in the Plugins Folder as `pyis-address-collection.old`. While it showed properly in the Plugins Listing and only the one we wanted to have active was active, it was pulling files from the old copy. It would seem that anything after a `.` simply gets truncated.

**Comment by d4mation** [comment]
Reported fixed in the latest beta.
